services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      # fixes bug in psycopg2 on m1 cpu https://stackoverflow.com/a/67482847
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  # amd64
  # chrome-server:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - "4444:4444"
  #   shm_size: '2gb'
  #   restart: always

  # arm64
  chrome-server:
    image: seleniarm/standalone-chromium:latest
    shm_size: '3gb'
    restart: always

  app:
    build: .
    environment:
      COMMAND_EXECUTOR: http://chrome-server:4444/wd/hub
      EXTENSIONS: /ext/runet-censorship-bypass.crx
      LOGGING_LEVEL: INFO
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
      - chrome-server
    volumes:
      - ./ext/:/ext/:ro